# Ajiya configuration: https://github.com/AliyuYahaya/Ajiya

[project]
name = "Ajiya"
prefix = "AJ"

# [launch]
# target = "go-live"          # a phase slug or a ticket ID

[test]
command = "go test ./..."   # run by 'ajiya ticket done --test'

# [[apps]]
# name = "api"
# path = "apps/api"

[[milestones]]
name = "v0-1"
targets = ["AJ-0034"]

[[milestones]]
name = "v0-2"
targets = ["AJ-0047"]

[[milestones]]
name = "v0-2-1"
targets = ["AJ-0098", "AJ-0099", "AJ-0100", "AJ-0101", "AJ-0102", "AJ-0103", "AJ-0104", "AJ-0105", "AJ-0106"]

[[milestones]]
name = "v0-3"
targets = ["AJ-0058"]

[[milestones]]
name = "after-v0-3"
targets = ["AJ-0057"]

[[apps]]
name = "ajiya"
path = "."
