# Ajiya configuration: https://github.com/AliyuYahaya/Ajiya

[project]
name = "Ajiya"
prefix = "AJ"

# [launch]
# target = "go-live"          # a phase slug or a ticket ID

[test]
command = "go test ./..."   # run by 'ajiya ticket done --test'

# [[apps]]
# name = "api"
# path = "apps/api"

[[apps]]
name = "ajiya"
path = "."
